-- LocalScript → StarterGui/SettingsMenu
-- NOTE: Settings UI is handled by Sidebar (SETTINGS tab).
-- This script is intentionally a no-op — kept as a placeholder.
-- All settings display logic lives in Sidebar.client.lua.
