-- LocalScript → StarterGui/DroneUI
-- NOTE: Drone UI is handled by Sidebar (DRONES tab).
-- This script is intentionally a no-op — kept as a placeholder.
-- All drone display logic lives in Sidebar.client.lua.
