-- LocalScript → StarterGui/InventoryUI
-- NOTE: Display is handled by Sidebar (CARGO tab).
-- This script is intentionally a no-op — kept as a placeholder.
-- All collectFragmentEvent / spendMaterialEvent handling lives in Sidebar.client.lua.
